# Customer Churn Data Cleaning and Preparation

## Project Overview

Customer Churn occurs when customers stop using a company's products or services.
This project focuses on cleaning and preparing a Telecommunicatins customer dataset for further analysis.
The main goal is to identify and address data quality issues such as 
Missing Values

Duplicate Records

Incorrect Data Types

Inconsistent Values 

Potential Outliers 

The cleaned dataset will provide a reliable foundation for subsequent Customer churn anlaysis.

## Busines  Problem 

Telecommunication companies need reliable customer data to understand customer behaviour and identify factors associated with customer churn 

Before performing analysis , the dataset must be examined and cleaned to ensure that the results are accurate and trustworthy.

This project therefore focuses on systematically assessing and improving the quality of the customer churn dataset

## Project Objectives 
The objectives of thus projects are to :

1. Understand the structure and characteristics of the raw dataset
2. Assess the quality of the data
3. Identify missing values and determine appropriate ways of handling them
4. Identify and investigate duplicated records from the dataset
5. Correct inappropriate and inconsistent data types
6. Identify inconsistent categorical values
7. Investigate potential outliers in the dataset
8. Validate the cleaned dataset
9. Save the cleaned dataset for future analysis

## Data Description

The dataset contains customer-level information from a telecommunication company.
It includes information about:

1. Customer Demographics
2. Services subscribed to
3. Contact Information
4. Payment Methods
5. Customer Tenure
6. Monthly Charges
7. Total Charges
8. Customer Churn Status

**N/B**
The target variable is *Churn* , which indicates whether a customer left the company.

## Data Source

The dataset used in this project is the TELCO CUSTOMER CHURN dataset , originally provided by **IBM**

Source: Telco Customer churn dataset

Original file: "Telco_Customer_churn.csv"

Dataset size : 7043 Records and 21 Variables

## data Inspection 

### Import Libraries

In [1]:
# import important libraries

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

### loading the dataset

In [2]:
df=pd.read_csv("Telco-Customer-Churn.csv")

# read the dataset , top 5

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
# Identifying the number of rows and columns 
df.shape

(7043, 21)

In [4]:
# Identifying the column names within the dataset
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [5]:
# getting the dataset summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

## DATA QUALITY ASSESSMENT

### STEP2: Assess Data's Missing Values 

Missing values can affect analysis and may need to be handled before the dataset is used for further analysis or modelling.

In this data cleaning process , we checked for data Completeness

FALSE: Not Missing
TRUE: Missing value

Observation : The dataset contained no missing values across all the 21 Variables, the dataset is 100% complete

In [6]:
# checking for missing values 
df.isnull()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [8]:
# Columns with the most missing values 

df.isnull().sum().sort_values(ascending=False)

customerID          0
DeviceProtection    0
TotalCharges        0
MonthlyCharges      0
PaymentMethod       0
PaperlessBilling    0
Contract            0
StreamingMovies     0
StreamingTV         0
TechSupport         0
OnlineBackup        0
gender              0
OnlineSecurity      0
InternetService     0
MultipleLines       0
PhoneService        0
tenure              0
Dependents          0
Partner             0
SeniorCitizen       0
Churn               0
dtype: int64

In [17]:
# getting a sample of the data to understand the structure

df.sample(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1329,3910-MRQOY,Female,0,Yes,No,72,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.40,1496.45,No
2910,5622-UEJFI,Female,0,Yes,Yes,35,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),25.40,949.8,No
1002,8120-JDCAM,Male,0,Yes,Yes,4,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,69.55,284.9,No
481,0447-BEMNG,Female,0,Yes,No,48,No,No phone service,DSL,Yes,...,Yes,No,No,Yes,Month-to-month,Yes,Bank transfer (automatic),45.30,2145,Yes
4651,3540-RZJYU,Female,0,No,No,15,Yes,No,Fiber optic,Yes,...,No,No,Yes,No,Month-to-month,No,Electronic check,86.20,1270.2,Yes
4114,1574-DYCWE,Female,0,Yes,Yes,51,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.95,1028.75,No
4197,5934-RMPOV,Female,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,84.75,1816.75,No
5853,9114-VEPUF,Male,0,Yes,No,62,Yes,Yes,Fiber optic,Yes,...,No,No,No,Yes,One year,No,Electronic check,96.10,6001.45,No
3431,2430-USGXP,Male,0,Yes,No,24,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,101.05,2391.8,Yes
873,5073-WXOYN,Female,0,No,No,60,No,No phone service,DSL,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,50.80,3027.4,Yes

In [18]:
## Checking for blank values

df["TotalCharges"].astype(str).str.strip().eq("").sum()

11

In [19]:
## Checking the entire dataset columns

(df.astype(str).apply(lambda x: x.str.strip().eq("")).sum())

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

#### How many columns have some missing values / blank values

from the above information , we observe that **TotalCharges** columns has the highest number of missing values with **11**.

The rest of the columns have *0* missing values 

*ACTION*

The missing values in the *TotalCharges* column will be further investigated to determine whether they represent genuine missing information or another data quality issue

### STEP2.2 CHECKING FOR DUPLICATED VALUES

Duplicate records can lead to inaccurate analysis because a customer may be counted more than once .

Therefore , duplicate rows were checked before proceeding with further analysis

In [22]:
# Checking and investigating duplicate records

df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Length: 7043, dtype: bool

In [23]:
# Total records with duplicated data

df.duplicated().sum()

0

##### OBSERVATION

The Telco-Customer-churn dataset contains **0** duplicated records.

This is useful and important for analysis 

Conclusion

No Duplicate rows were identified.

Therefore no duplicate records need to be removed , hence the dataset can proceed to the next stage of the data cleaning process.